### PR TITLE
upgrade to yarn v3

### PR DESCRIPTION
**Pull request by sachinraja**
Noticed this package was still using yarn v1. This PR updates it to yarn v3. I had to delete a lot of `package.json` files from the fixtures because they confused yarn when it attempted to find the package root. It resolves `tsc` from there anyway (before a script explicitly linking to the bin was used).

### CODE REVIEW

**Comment by piglovesyou** [comment]
This is so nice, thank you @sachinraja. Removing all the package.json files make it so clean.

I'm still unfamiliar with Yarn v3, could you take a look at the CI failure? I confirmed it passes all tests locally.

**Comment by sachinraja** [comment]
Seems to be the same error as yarnpkg/berry#3191, I'll see if setting the version `from sources` fixes it.

**Comment by sachinraja** [comment]
This should work now if you approve the workflow.

**Comment by piglovesyou** [comment]
Thank you @sachinraja, I could never do this without you!

**Comment by sachinraja** [comment]
Looks like dependabot is failing because it doesn't support yarn >=2 (see dependabot/dependabot-core#1297). I recommend switching to [renovate](https://docs.renovatebot.com/), which has already added support and has a lot more features.

**Comment by piglovesyou** [comment]
That's a helpful tip. Renovate seems nice. I've been thinking Dependabot hasn't worked as expected after being GitHub-native. I'll check it when I get time.

**Pull request merged**
