### PR TITLE
Accept `configFile` option in webpack loader

### PR DESCRIPTION
**Pull request by hasparus**
I didn't say hello previously, so

Hi! :wave: Nice to meet you!
First thing I wanted to say, graphql-let is freaking awesome.

I hope this PR can serve as a first step towards closing #79, and problems I mentioned https://github.com/piglovesyou/graphql-let/issues/79#issuecomment-689706623.
I'll be happy to do any changes or fixes required.

---

I'm not a huge fan of how the options validation is sorted out -- schema and the type are separate and can diverge if one doesn't pay attention -- however despite it seems _inferior from usage perspective_ to io-ts or ts-json-validator, it's an official/conventional webpack package and gives really good messages to loader users.

### CODE REVIEW

**Comment by piglovesyou** [comment]
@hasparus I agree about JSON Schema, it could be just a TypeScript type, but here we can start both a type and a schema. Recently, I worked on a project where Git manages types and only the production package includes generated JSON Schemas, by the way. I guess the decision depends on the size of the redundancy.

So, would you like to fix the CI failure? And it seems we need `@types/schema-utils` according to my quick local try. Tell me if you'd like me to do the rest.

**Comment by hasparus** [comment]
`schema-utils` 2.7 is actually written in TypeScript.

The problem with CI is that I used optional chaining in the test, so it doesn't work on Node 12.

**Comment by piglovesyou** [comment]
I see, thanks. I'll wait until it passes, please ask me if you want me to work on it.

**Comment by hasparus** [comment]
No problem! Sorry for tardiness.

I tweaked the test TypeScript config and reduced the error to a situation where it works on my laptop, and not on CI :rofl:

**Comment by hasparus** [comment]
I'll waste some more electicity on GitHub Actions servers, because `nvm` doesn't help me here. Sorry for the notifications spam you're getting :pray:

**Comment by hasparus** [comment]
Okay, the error is pretty weird. The generated file seems to be empty and then `src/fruits.graphql was generated.` is logged.

```
    Snapshot name: `graphql-let/loader accepts config path in \`options.configFile\` 2`

    - Snapshot  - 1
    + Received  + 0

    @@ -1,6 +1,5 @@
    -
      import { gql } from '@apollo/client';
      import * as Apollo from '@apollo/client';
      export const GetFruitsDocument = gql`
          query GetFruits {
        fruits {

      89 |     expect(
      90 |       generated.source?.replace(/\/\*[\s\S]*?\*\//g, ''),
    > 91 |     ).toMatchSnapshot();
         |       ^
      92 |   });
      93 | });
      94 | 

      at Object.<anonymous> (loader.test.ts:91:7)

 › 1 snapshot failed.
[ graphql-let ] src/fruits.graphql was generated.
```

I'll take a look at it this weekend.

**Comment by hasparus** [comment]
hey @piglovesyou, I got these tests to work

**Comment by piglovesyou** [comment]
@hasparus Thank you for the work! 0.16.1 includes your change.
From my local test execution, I also couldn't know why we need `waitOn`. I think I'll make another issue for that.

**Comment by hasparus** [comment]
Thanks! Happy to help (and remove that duplicated .graphql-let.yml from my monorepo :shushing_face:).

> From my local test execution, I also couldn't know why we need waitOn. I think I'll make another issue for that.

`generated.source` was supposedly empty, but I can't understand why, and why I couldn't reproduce it locally.

**Pull request merged**
